apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpletickr.frontend.fullname" . }}
  labels:
    {{- include "simpletickr.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "simpletickr.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simpletickr.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "simpletickr.frontend.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PUBLIC_API_BASE_URL
              value: {{ include "simpletickr.frontend.apiBaseUrl" . | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
